import odm2.automap_models.annotations as annotations
import odm2.automap_models.core as core
import odm2.automap_models.cv as cv
import odm2.automap_models.dataquality as dataquality
import odm2.automap_models.equipment as equipment
import odm2.automap_models.extensionproperties as extensionproperties
import odm2.automap_models.externalidentifiers as externalidentifiers
import odm2.automap_models.labanalyses as labanalyses
import odm2.automap_models.provenance as provenance
import odm2.automap_models.results as results
import odm2.automap_models.samplingfeatures as samplingfeatures
import odm2.automap_models.simulation as simulation
